[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "cd tradetaper-backend",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd tradetaper-backend",
  "npm run build"
]

[start]
cmd = "cd tradetaper-backend && node dist/main"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 