[build]
  builder = "nixpacks"
  buildCommand = "cd tradetaper-backend && npm install --legacy-peer-deps && npm run build"

[deploy]
  startCommand = "cd tradetaper-backend && node dist/main"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 60
  healthcheckInterval = 10
  restartPolicyType = "always"
  restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"
PORT = "3000"
NODE_OPTIONS = "--max-old-space-size=2048"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 