[build]
  builder = "NIXPACKS"
  buildCommand = "cd tradetaper-backend && npm install && npm run build"

[deploy]
  startCommand = "cd tradetaper-backend && npm run start:prod"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000" 