runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  DB_USER: 'tradetaper-backend-sa@tradetaper.iam.gserviceaccount.com'
  DB_NAME: 'tradetaper'
  INSTANCE_CONNECTION_NAME: 'tradetaper:us-central1:tradetaper-postgres'

beta_settings:
  cloud_sql_instances: 'tradetaper:us-central1:tradetaper-postgres'

vpc_access_connector:
  name: 'projects/tradetaper/locations/us-central1/connectors/tradetaper-connector'

entrypoint: 'npm run start:prod' 