# cloudbuild.yaml for tradetaper-backend

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tradetaper-backend:$COMMIT_SHA', '.']
    dir: 'tradetaper-backend'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tradetaper-backend:$COMMIT_SHA']
    dir: 'tradetaper-backend'

  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'tradetaper-backend',
      '--image',
      'gcr.io/$PROJECT_ID/tradetaper-backend:$COMMIT_SHA',
      '--region',
      'us-central1', # Or your preferred region
      '--platform',
      'managed',
      '--allow-unauthenticated', # Adjust as per your authentication needs
      '--add-cloudsql-instances', # Placeholder for Cloud SQL connection
      '$PROJECT_ID:us-central1:your-cloud-sql-instance', # Replace with your Cloud SQL instance connection name
      '--set-env-vars', # Placeholder for environment variables
      'DATABASE_URL=your_database_url,JWT_SECRET=your_jwt_secret,GOOGLE_CLIENT_ID=your_google_client_id,GOOGLE_CLIENT_SECRET=your_google_client_secret,STRIPE_SECRET_KEY=your_stripe_secret_key,METAAPI_TOKEN=your_metaapi_token,METAAPI_ACCOUNT_ID=your_metaapi_account_id,GCS_BUCKET_NAME=your_gcs_bucket_name,GEMINI_API_KEY=your_gemini_api_key'
    ]
    dir: 'tradetaper-backend'

images:
  - 'gcr.io/$PROJECT_ID/tradetaper-backend:$COMMIT_SHA'