# cloudbuild.yaml for tradetaper-backend

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tradetaper-backend:latest', '.']
    id: 'Build'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tradetaper-backend:latest']
    waitFor: ['Build']
    id: 'Push'

  # Deploy the image to Cloud Run, using a secret for the DB password
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tradetaper-backend'
      - '--image=gcr.io/$PROJECT_ID/tradetaper-backend:latest'
      - '--region=us-central1' # Specify your desired region
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--add-cloudsql-instances=tradetaper:us-central1:tradetaper-postgres'
      - '--update-secrets=DB_PASSWORD=TRADETAPER_DB_PASSWORD:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--set-env-vars=NODE_ENV=production,DB_USER=tradetaper-backend-sa@tradetaper.iam.gserviceaccount.com,DB_NAME=tradetaper,INSTANCE_CONNECTION_NAME=tradetaper:us-central1:tradetaper-postgres'
    id: 'Deploy'
    waitFor: ['Push']
    entrypoint: 'gcloud'

images:
  - 'gcr.io/$PROJECT_ID/tradetaper-backend:latest'
