[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm run start:prod"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 300
  restartPolicyType = "always"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000"
  RUN_MIGRATIONS = "true"
  FRONTEND_URL = "https://tradetaper-frontend-benniejosephs-projects.vercel.app" 