[build]
  builder = "nixpacks"
  buildCommand = "npm install --legacy-peer-deps && npm run build:simple"
  watchPatterns = ["**/*.ts", "**/*.js", "**/*.json"]

[deploy]
  startCommand = "node dist/main"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 300
  healthcheckInterval = 30
  restartPolicyType = "always"
  restartPolicyMaxRetries = 3

[variables]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=2048"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  FRONTEND_URL = "https://tradetaper-frontend-benniejosephs-projects.vercel.app" 