[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "./start-production.sh"
  healthcheckPath = "/api/v1/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000"
  RUN_MIGRATIONS = "true"
  FRONTEND_URL = "https://tradetaper-frontend-benniejosephs-projects.vercel.app" 