[build]
  builder = "nixpacks"
  buildCommand = "npm install --legacy-peer-deps && npm run build"
  watchPatterns = ["**/*.ts", "**/*.js", "**/*.json"]

[deploy]
  startCommand = "node dist/main"
  healthcheckPath = "/health"
  healthcheckTimeout = 60
  healthcheckInterval = 10
  restartPolicyType = "always"
  restartPolicyMaxRetries = 5

[variables]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=2048"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  FRONTEND_URL = "https://tradetaper-frontend-benniejosephs-projects.vercel.app" 