[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm run start:prod"
  healthcheckPath = "/api/v1"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000" 