[build]
  builder = "dockerfile"

[deploy]
  startCommand = "node dist/main"
  healthcheckPath = "/api/v1/ping"
  healthcheckTimeout = 120
  restartPolicyType = "always"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
  PORT = "3000"
  RUN_MIGRATIONS = "true"
  FRONTEND_URL = "https://tradetaper-frontend-benniejosephs-projects.vercel.app" 